CREATE DATABASE IF NOT EXISTS `project`;
USE `project`;

CREATE TABLE IF NOT EXISTS `users`(
`id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`email` VARCHAR(64) NOT NULL,
`password` VARCHAR(32) NOT NULL,
`name` VARCHAR(16) NOT NULL,
`surname`  VARCHAR(16) NOT NULL, 
`gender` VARCHAR(8) NOT NULL, /* null*/
`birthday` DATE NOT NULL, /* null*/
`avatar` INT(2) NOT NULL DEFAULT 0
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `surveys`(
`id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`title`  VARCHAR(128) NOT NULL,
`user_id` INT(16) NOT NULL,
`privacy` INT(2) NOT NULL DEFAULT 0,
`privacy_password` VARCHAR(32) NOT NULL,
`avatar` INT(2) NOT NULL DEFAULT 0
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `surveys_questions`(
`id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`survey_id` INT(16) NOT NULL,
`content` LONGTEXT NOT NULL,
`type` VARCHAR(16) NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `surveys_answers`(
`id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`user_id` INT(16) NOT NULL,
`question_id` INT(16) NOT NULL,
`answer` VARCHAR(256) NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;